# Generated by Django 5.1.3 on 2025-05-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expansion', models.CharField(max_length=10)),
                ('file_data', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Бесплатный контент',
                'verbose_name_plural': 'Бесплатный контент',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_paid', models.DateTimeField()),
                ('time_paid', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
    ]
