# Generated by Django 5.1.3 on 2025-05-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binarydocument',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AddField(
            model_name='binarydocument',
            name='status_file',
            field=models.CharField(choices=[('FREE', 'Бесплатный контент'), ('RASS', 'Рассылка')], default='FREE', max_length=10),
        ),
    ]
