# Generated by Django 5.1.3 on 2025-05-23 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_inputtext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputtext',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылка'},
        ),
        migrations.AddField(
            model_name='inputtext',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='inputtext',
            table='spam_messages',
        ),
    ]
