# Generated by Django 5.1.3 on 2025-05-23 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_inputtext_options_inputtext_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
