# Generated by Django 5.1.3 on 2025-05-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_client_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='is_paid',
            new_name='is_paid_cheap_content',
        ),
        migrations.AddField(
            model_name='client',
            name='is_paid_expensive_content',
            field=models.BooleanField(default=False),
        ),
    ]
