# Generated by Django 5.1.3 on 2025-05-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_is_paid_client_is_paid_cheap_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelloMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Приветственное сообщение')),
            ],
            options={
                'verbose_name': 'Приветственное сообщение',
                'verbose_name_plural': 'Приветственное сообщение',
                'db_table': 'hello_message',
            },
        ),
        migrations.CreateModel(
            name='HelpChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Username чата')),
            ],
            options={
                'verbose_name': 'чат помощи',
                'verbose_name_plural': 'чаты помощи',
                'db_table': 'help_chat',
            },
        ),
        migrations.CreateModel(
            name='PaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('btn_text', models.CharField(max_length=255, verbose_name='Текст кнопки')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка на канал')),
            ],
            options={
                'verbose_name': 'Настройка оплаты',
                'verbose_name_plural': 'Настройки оплаты',
                'db_table': 'pay_settings',
            },
        ),
    ]
