# Generated by Django 5.1.3 on 2025-05-24 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_hellomessage_helpchat_paysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hellomessage',
            name='user_friendly_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Уникальный идентификатор(не менять, в случае удаления строки, добавить новую с тем же id, или все сломается)'),
        ),
        migrations.AddField(
            model_name='helpchat',
            name='user_friendly_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Уникальный идентификатор(не менять, в случае удаления строки, добавить новую с тем же id, или все сломается)'),
        ),
        migrations.AddField(
            model_name='paysettings',
            name='user_friendly_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Уникальный идентификатор(не менять, в случае удаления строки, добавить новую с тем же id, или все сломается)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Телеграм ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_paid_cheap_content',
            field=models.BooleanField(default=False, verbose_name='Оплачен дешевый контент'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_paid_expensive_content',
            field=models.BooleanField(default=False, verbose_name='Оплачен дорогой контент'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time_paid',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время оплаты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
    ]
