# Generated by Django 5.1.3 on 2025-05-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_hellomessage_user_friendly_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysettings',
            name='id_chanel',
            field=models.IntegerField(blank=True, null=True, verbose_name='id канала'),
        ),
    ]
