# Generated by Django 5.1.3 on 2025-05-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_paysettings_id_chanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysettings',
            name='id_chanel',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='id канала'),
        ),
    ]
