# Generated by Django 5.1.3 on 2025-05-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_paysettings_id_chanel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='time_paid',
        ),
    ]
